### ISSUE TITLE
The performance of the pretrained model you provided is somewhat different

### ISSUE THREAD

**Issue by tfygg** [natanielruiz/deep-head-pose#1]
Hi, i tested the pretrained model (300W-LP, alpha 2) you provided on AFLW2000, and found that the performance is somewhat different from shown on the paper? is this model the best of your algorithm?

![image](https://user-images.githubusercontent.com/12944493/33471889-614a939c-d6aa-11e7-9e76-72edada84e42.png)

**Comment by natanielruiz** [comment]
![image](https://user-images.githubusercontent.com/16767288/33488004-3da72f4a-d67d-11e7-9ed0-fccf93c76580.png)

**Comment by natanielruiz** [comment]
Oh by the way I can send you the image list that I use for AFLW2000 by email if you want :smile:

**Comment by natanielruiz** [comment]
Please tell me if this fixed the mismatch, also check if you're using the test_hopenet.py script to test it. Thank you!

**Comment by tfygg** [comment]
Ok, thanks. My email is tfy07@qq.com.
By the way, When trained the model, should i filter the datasets and remove the images?
 Can you send me the image list for train?

**Comment by tfygg** [comment]
Thank for your help.
I used the image list that your provided, the accuracies is no problem.

**Comment by Zouhj** [comment]
Could you please send the image list which you use for AFLW2000 to me? My email is 964756048@qq.com.   Thank you very much! @natanielruiz

**Comment by tangbohu** [comment]
Dear Natanielruiz, could you also send me the image list?
My email is tangbohutbh@gmail.com. Thanks a lot!

**Comment by fengziyong** [comment]
@tfygg @natanielruiz 
I filtered the 300W_LP and AFLW2000 by myself. But I can't reproduce result reported by the paper.
![test](https://user-images.githubusercontent.com/23159053/41188064-882dd688-6bea-11e8-95f1-8a41bc3b5eda.png)
I train on 300W_LP and test on AFLW200.  
Settings:
`python train_hopenet.py --output_string=2018-06-09_1 --data_dir=../data --filename_list=../pose_clean.list --alpha=1 --lr=0.00001 --gpu 3 --num_epochs 25`

**Comment by GKG1312** [comment]
Hi @natanielruiz, 
I am testing pre-trained model `hopenet_robust_alpha1.pkl` with the following settings
`test_hopenet.py --data_dir ".\AFLW2000" --filename_list ".\AFLW2000_filename_filtered.txt" --snapshot ".\hopenet_robust_alpha1.pkl" --batch_size 1 `
But I am not able to acheive mentioned accuracies in Yaw and Pitch. I am getting following:

> Test error in degrees of the model on the 1969 test images. Yaw: 9.1709, Pitch: 7.0361, Roll: 5.7762

Can you help me figure it out. I am using the filtered filename list provided by you on #6 [here](https://github.com/natanielruiz/deep-head-pose/issues/6#issuecomment-353727741).

**Comment by Zouhj** [comment]
Thank you for your email. I'll disposal and reply as soon as possible.Best Regards!邹涵江
