### ISSUE TITLE
*_shape.npy files

### ISSUE THREAD

**Issue by numitors** [natanielruiz/deep-head-pose#11]
I wanted to retrain your model, have downloaded the 300W-LP dataset, but I am unable to find .npy files needed. I see that other datasets do not use them, so I tried to remove them the same way it is done for other datasets, but that causes an error. Any insight about this?

**Comment by developer-mayuan** [comment]
@numitors I don't think you need the .npy files. You just need to generate a list of files in the 300W-LP dataset, then the program will automatic load the .jpg and .mat file and preprocess the data and generate a Dataset class for it.

Following below is a filelist generated by myself.

[filelist.txt](https://github.com/natanielruiz/deep-head-pose/files/1626970/filelist.txt)

**Comment by numitors** [comment]
@developer-mayuan Thanks for the reply, this is exactly what I did, generated file list first, but when I run it i get the fillowing:
`Epoch [1/5], Iter [100/7653] Losses: Yaw 9.6049, Pitch 4.4158, Roll 5.3993
Epoch [1/5], Iter [200/7653] Losses: Yaw 8.0809, Pitch 3.0956, Roll 2.6524
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:57: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
CUDA error after cudaEventDestroy in future dtor: device-side assert triggeredTraceback (most recent call last):
  File "code/train_hopenet.py", line 169, in <module>
    loss_reg_yaw = reg_criterion(yaw_predicted, label_yaw_cont)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/loss.py", line 272, in forward
    return F.mse_loss(input, target, size_average=self.size_average)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 819, in mse_loss
    return _functions.thnn.MSELoss.apply(input, target, size_average)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/thnn/auto.py", line 47, in forward
    output, *ctx.additional_args)
RuntimeError: cudaEventSynchronize in future::wait: device-side assert triggered
`
I thought something was wrong with my approach that is why I asked for help.

**Comment by natanielruiz** [comment]
@developer-mayuan Thank you for your reply, I believe that issue will solve @numitors problem.
