### ISSUE TITLE
i think there are some typos in code

### ISSUE THREAD

**Issue by jhk623** [natanielruiz/deep-head-pose#12]
hi natanielruiz im a beginner student of DL, and thank you for opening really great source for us

anyway, i think i found some typo in your code of
https://github.com/natanielruiz/deep-head-pose/blob/610c14dad563224b973c6a2f24b5d285d5ca9672/code/datasets.py#L187

i think it should be like
pose = utils.get_ypr_from_mat(mat_path)
pitch = pose[0] * 180 / np.pi

thanks :)

**Comment by natanielruiz** [comment]
Thanks a lot! It's fixed now.
