### ISSUE TITLE
when I run the code  test_on_video_dlib.py  using hopenet_alpha1.pkl

### ISSUE THREAD

**Issue by dequecolor** [natanielruiz/deep-head-pose#15]
error message:

Traceback (most recent call last):

  File "/home/hhf/桌面/deep-head-pose-master/code/test_on_video_dlib.py", line 59, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(args.face_model)

RuntimeError: An error occurred while trying to read the first object from the file /home/hhf/桌面/hopenet_alpha1.pkl.
ERROR: Error deserializing object of type int

I don't know what's the reason for this error.

**Comment by marouabenzarti** [comment]
How did you solve this problem ?

**Comment by NguyenDangBinh** [comment]
dear,
I had the same but I replaced shape_predictor_68_face_landmarks.dat by mmod_human_face_detector.dat. It ran.

**Comment by yurt9797** [comment]
> 

How did you replace shape_predictor_68_face_landmarks.dat by mmod_human_face_detector.dat?
