### ISSUE TITLE
is there any reason using degree rather than radian??

### ISSUE THREAD

**Issue by jhk623** [natanielruiz/deep-head-pose#16]
hi nataniel ruiz! i am a student who began studying ML and i have a question for your great work
first i want to thank you for providing your good code and insight.
my question is
in the code, you used degree instead of radian
but i think radian is easier to get regressed because it is only from -2pi to 2pi.
is there any reason??

thank you

**Comment by natanielruiz** [comment]
I limit the prediction to [-99,+99] degrees since most training data has that range. It probably would work with radians, the regression loss would have lesser magnitude and you might need to adjust the alpha coefficient accordingly - that's probably the only difference.
