### ISSUE TITLE
When trained the model

### ISSUE THREAD

**Issue by tfygg** [natanielruiz/deep-head-pose#2]
hi, natanielruiz
i use your code to train the model: 
`python code/train_hopenet.py --data_dir /AFLW2000/AFLW2000 --filename_list AFLW2000/imglist.txt`
but  there is the bug:
![image](https://user-images.githubusercontent.com/12944493/33533161-40af0852-d8da-11e7-88db-59ed33f33e28.png)
how to modify the code? and hope you can give the lastest code.

**Comment by natanielruiz** [comment]
Ohh I see. I had some experiments using shape parameters of faces - I will fix this today. By the way I am sharing the latest code base, this is not outdated code. It just takes a little bit of time to clean up all of the experiments that didn't work out.

**Comment by tfygg** [comment]
OK. I am waiting for it.
Can you give me your email? I have some questions about deep-head-pose. Thanks very much!

**Comment by natanielruiz** [comment]
Hi @tfygg, you can go to my website for my email.

Please give me a couple of days to correct the code and send you the filename list. I am currently a little busy. Thank you.

**Comment by natanielruiz** [comment]
This has been fixed in commit [9f2fa4a5fa2af40503c05379c9d5318e87581c7b](https://github.com/natanielruiz/deep-head-pose/commit/9f2fa4a5fa2af40503c05379c9d5318e87581c7b). Please comment if you find any issues.
