### ISSUE TITLE
To test the code on CPU

### ISSUE THREAD

**Issue by abhigoku10** [natanielruiz/deep-head-pose#20]
@natanielruiz  hi thanks for the code , can you point out the changes to be made to run the test code on cput 

Thanks in advance

**Comment by natanielruiz** [comment]
Hi @abhigoku10 
The code is not quite designed for cpu usage although making it compatible shouldn't be hard. Just remove all .gpu() conversion of tensors and variables.

Basically if you have
`pose.gpu()`

Then delete this line.

If you have 
`new_variable = Variable(tensor.gpu())`
Replace with
`new_variable = Variable(tensor)`

etc.

Don't hesitate to re-open if you have trouble.

**Comment by abhigoku10** [comment]
@natanielruiz  thanks for the tips , i did as suggested it worked , the draw back is its slow and at the same time it process only 10 frames of a video
