### ISSUE TITLE
About the BIWI dataset

### ISSUE THREAD

**Issue by shamangary** [natanielruiz/deep-head-pose#23]
Hi. Thank you for the great project.
About BIWI dataset, I have some question about the face detection.
I understand that you use your Dockerface for the face detection.
I try to replace the preprocess by MTCNN for the face detection, but there will be some missing frames due to the large pose.
Using the previous frame detection location can be a solution, but I found it could lead to a great performance drop. Can you tell me how do you handle these kinds of situation when dockerface fail?
The training code does not reflect this problem. Thank you!

**Comment by natanielruiz** [comment]
Hi @shamangary thanks so much!

We don't detect pose for the frames dockerface misses. It is pretty accurate but there are going to be some missed frames. We don't have any temporal tracking solution but you could try to use something like this. I don't know much about tracking so you should start looking for code or papers online. Just remember the bounding box input has to be in dockerface format and that's it! You can do whatever you want :)

It is not a problem with the training code. In every image we either have face bounding boxes or not and we use those bounding boxes to obtain the cropped face as an input to our network.

**Comment by shamangary** [comment]
Thank you I understand now. If I take every single frame, I will get 15678 samples. While I use the detected frame only, I will get 13219 samples. May I have the number of samples for your dockerface implementation?

**Comment by natanielruiz** [comment]
I don't know. You can use it yourself at github.com/natanielruiz/dockerface

**Comment by yafeiliu666** [comment]
@shamangary Hi, if you have the face detection file, I hope you can give me, thank you very much!

**Comment by shamangary** [comment]
@yafeiliu666 I have pre-processed the face images using mtcnn which is not exactly the same with dockerface though. You may check this link: https://github.com/shamangary/FSA-Net
