### ISSUE TITLE
result is not good when yaw or pitch angle is large

### ISSUE THREAD

**Issue by junedgar** [natanielruiz/deep-head-pose#24]
The result is not good when yaw or pitch angle is large. we can find the yaw anlge for the image below is almost 90°，but predicted yaw angle is about 40°。
![1234](https://user-images.githubusercontent.com/17995658/42307311-8b98a5da-8064-11e8-8b0f-d7ad319b5879.jpg)

**Comment by natanielruiz** [comment]
Okay.
I don't really know what you want me to say to this except:
-We never claim that we achieve perfect, infallible head pose estimation.
-Check if the bounding box is correct

**Comment by junedgar** [comment]
@natanielruiz 
Thank you for your reply and sorry to trouble you!
It's really a great work! 
May be you can give me some advices to improve these cases?
I checked these cases' bounding box, they were correct.

**Comment by xmba15** [comment]
Just to let you know the result I tested on the above image for yaw, pitch, roll
```
tensor(80.7385, device='cuda:0')
tensor(-20.5594, device='cuda:0')
tensor(-22.6370, device='cuda:0')
```
Good job.
