### ISSUE TITLE
train the model on 300W_LP reports the cuda runtime error

### ISSUE THREAD

**Issue by java63940** [natanielruiz/deep-head-pose#27]
Hi natanielruiz, thanks a lot to open source your project, I use your model to test my video, it behavies very good.
Now I want to train your model on 300W_LP:

**python code/train_hopenet.py --data_dir=300W_LP --filename_list=filename_list**

When the train process run several thousands images, he crash and report the following errors:

### /THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [16,0,0] Assertion t >= 0 && t < n_classes failed.

It crashs at train_hopenet.py:177, when access "yaw_predicted"

Any ideas ? thinks

**Comment by java63940** [comment]
solved.
https://github.com/natanielruiz/deep-head-pose/issues/6

**Comment by MoonBunnyZZZ** [comment]
where to download the 300W_LP dataset? Thank you! @java63940
