### ISSUE TITLE
Flip, Blur?

### ISSUE THREAD

**Issue by LingQiu** [natanielruiz/deep-head-pose#29]
hello, i want to know the meaning of these codes in the `datasets.py`:
`      # Flip?
       rnd = np.random.random_sample()
       if rnd < 0.5:
           yaw = -yaw
           roll = -roll
           img = img.transpose(Image.FLIP_LEFT_RIGHT)

        # Blur?
        rnd = np.random.random_sample()
        if rnd < 0.05:
            img = img.filter(ImageFilter.BLUR)`
thx.

**Comment by natanielruiz** [comment]
The flip part flips the image vertically (as well as the labels) with a 50% chance.
The blur part blurs the image using a gaussian filter with 5% chance.

**Comment by LingQiu** [comment]
I don't understand why this part is added.
