### ISSUE TITLE
I made an error when I was executing Python

### ISSUE THREAD

**Issue by ytgcljj** [natanielruiz/deep-head-pose#3]
File "code/test_on_video_dlib.py", line 7, in <module>
    import torch
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS

**Comment by natanielruiz** [comment]
I believe something is wrong with your OpenCV installation. This has happened to me when I had two versions of opencv-python installed (one from source one from pip).

Please update if this is the source of the issue.

**Comment by natanielruiz** [comment]
@ytgcljj any luck?

**Comment by ytgcljj** [comment]
@natanielruiz 
I reinstall the system,i run python code/test_on_video_dlib.py --snapshot PATH_OF_SNAPSHOT --face_model PATH_OF_DLIB_MODEL --video PATH_OF_VIDEO --output_string STRING_TO_APPEND_TO_OUTPUT --n_frames N_OF_FRAMES_TO_PROCESS --fps FPS_OF_SOURCE_VIDEO ,error invalid int value : `N_OF_FRAMES_TO_PROCESS`

**Comment by ytgcljj** [comment]
I don't know what PATH_OF_SNAPSHOT means, install the path, or be a constant

**Comment by natanielruiz** [comment]
That path is the path of the pre-trained model.

**Comment by natanielruiz** [comment]
Closing this issue.
