### ISSUE TITLE
How to do batch processing?

### ISSUE THREAD

**Issue by exnx** [natanielruiz/deep-head-pose#31]
Hi, is there a way to do a batch process, say of 10 frames, at a time?

Actually, I altered it to just process one cropped face at a time.  I can now run it on CPU this way, at about 0.7 secs/face.  Each face is about 100 to 200 pixels squared.

So now, I'd like to forward propagate multiple frames, or faces, at a time.  Any tips would be great, thanks!

Eric

**Comment by exnx** [comment]
@natanielruiz is there a way to pass multiple frames through the CNN?

**Comment by natanielruiz** [comment]
There is, but I don't have enough time to work on it. Check the testing scripts and try to figure out how to do it. If I were you I would preprocess images (ie. detect faces, crop faces and save images) and then use the network on top of this.

Cheers

**Comment by exnx** [comment]
@natanielruiz Yeap! That's what I did!  I'm just having trouble altering the code to forward propagate multiple images at once.

What I did was crop multiple faces in a single frame, transformed them (to get them the same size), and stacked them into a single tensor.

I passed this single tensor to the CNN, however, what I received back I could not get correct yaw, pitch roll values :(

Do you have any quick tips on what I'm supposed to get back (or how to correctly forward propagate a stacked frame) to the CNN?  Thanks so much!

**Comment by natanielruiz** [comment]
Sorry I have no free time for this :( I hope you found a solution. If you did please share it with everyone or send a pull request
