### ISSUE TITLE
About paper FAN

### ISSUE THREAD

**Issue by shamangary** [natanielruiz/deep-head-pose#32]
Hello. I want to know the FAN type mentioned in the paper.
Since there are four FAN pre-trained model in their github, I just want to make sure I check the right one.
https://github.com/1adrianb/2D-and-3D-face-alignment
```
    2D-FAN - trained on 300W-LP and finetuned on iBUG training set.

    3D-FAN - trained on 300W-LP

    2D-to-3D-FAN - trained on 300W-LP

    3D-FAN-depth - trained on 300W-LP
```
I suppose your FAN means 3D-FAN. Is that correct? Thank you!

**Comment by natanielruiz** [comment]
No, I believe we're using the 2D-FAN since we use 2D to 3D correspondence to obtain the head pose.

Cheers!
