### ISSUE TITLE
how doese fc_finetune work

### ISSUE THREAD

**Issue by RunningLeon** [natanielruiz/deep-head-pose#38]
Hello,
Thanks for your great job.
Currently I'm trying to reimplement Hopenet in tensorpack. Could you pls. kindly answer following question:
1. How does fc_finetune layer work in hopenet? Is it being ignored?
         # Vestigial layer from previous experiments
        self.fc_finetune = nn.Linear(512 * block.expansion + 3, 3)

Thanks a lot.

**Comment by natanielruiz** [comment]
Yeah that one is ignored, it was an experiment that didn't improve results :P
