### ISSUE TITLE
Hi,natanielruiz.  Could you tell me how to run the code correctly?

### ISSUE THREAD

**Issue by Blacken23** [natanielruiz/deep-head-pose#4]
Hi,natanielruiz.  
 I'm a student who has just started to learn DeepLearning. I have installed the anaconda3 and pytorch and so on. I try to run your code : 

`python code/test_on_video_dockerface.py --snapshot PATH_OF_SNAPSHOT --video PATH_OF_VIDEO --bboxes FACE_BOUNDING_BOX_ANNOTATIONS --output_string STRING_TO_APPEND_TO_OUTPUT --n_frames N_OF_FRAMES_TO_PROCESS --fps FPS_OF_SOURCE_VIDEO`

and there is some errors:

```
Reloaded modules: datasets, utils, hopenet
Traceback (most recent call last):

  File "<ipython-input-9-5912a37fc872>", line 1, in <module>
    runfile('/home/deep/文档/deep-head-pose-master/code/test_on_video_dockerface.py', wdir='/home/deep/文档/deep-head-pose-master/code')

  File "/home/deep/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/home/deep/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/deep/文档/deep-head-pose-master/code/test_on_video_dockerface.py", line 48, in <module>
    if not os.path.exists(args.video_path):

  File "/home/deep/anaconda3/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

I don't  know what I did is right or not. I want to achieve the effect you show in the video.  Could you tell me how to run your code correctly?Thank you very much!

**Comment by natanielruiz** [comment]
Hello,
You have to provide paths to all of the requisite files, namely: path to the model snapshot which is downloadable from the link in the README, path to the video you want to process, path to the bounding box annotations that you have obtained from running dockerface (linked in the README) on the video. You also have to specify all of the other parameters for the script.

I think the flags have pretty self explanatory names and accurate descriptions.
Good luck.

**Comment by Blacken23** [comment]
Thank you very much!(^し^)
