### ISSUE TITLE
Image preprocess

### ISSUE THREAD

**Issue by hudingchang** [natanielruiz/deep-head-pose#40]
@natanielruiz 
<br>
It seems that the way of **image preprocessing (mainly bounding box padding)** differs in different py-files.
I wonder if there is any standard (or we can say rule) of image padding? 
Thank you very much.
<br>
**test_on_video_dlib.py** 
<pre>
x_min -= 2 * bbox_width / 4
x_max += 2 * bbox_width / 4
y_min -= 3 * bbox_height / 4
y_max += bbox_height / 4
</pre>
**test_on_video.py   &&   test_on_video_dockerface.py**
<pre>
x_min -= 50
x_max += 50
y_min -= 50
y_max += 30
</pre>

**Comment by natanielruiz** [comment]
It really depends on the "tightness" of the bounding box around the face. You basically don't want a bounding box that is too tight. I know it's not great to have absolute values for the expanding of the bounding box, you can change those.

**Comment by trohit920** [comment]
@natanielruiz  I have a simple question. Why with the changes in bounding box padding affecting the Euler Angles ? We test the code with tight bounding box (exact face) and one with defaults values and result have significant difference in Euler Angles for same input frame. Can you please specify the cause of that ? Also which Euler Angles are correct in this case ?
