### ISSUE TITLE
Test Score on AFLW2000 

### ISSUE THREAD

**Issue by nebojsaandelkovic** [natanielruiz/deep-head-pose#41]
@natanielruiz I am trying to evaluate the following model:
https://drive.google.com/open?id=1m25PrSE7g9D2q2XJVMR6IA7RaCvWSzCR
on AFLW2000 dataset (31 images with angles outside of range -99-99 are eliminated) with test_hopenet.py and I am getting the follwoing error scores:
Test error on the 1969 test images. Yaw: 9.1709, Pitch: 7.0361, Roll: 5.7762, MAE: 7.3277
however in the papre, reported error (for alpha=1) are: Yaw: 6.920, Pitch: 6.637, Roll: 5.674, MAE: 6.410

Can you please upload the right model or give some instructions how to reproduce results? Thanks in advance.

**Comment by nebojsaandelkovic** [comment]
@natanielruiz sorry, my bad, I tried other two models provided and it is fine with them. I was not aware that robust one performes worse on AFLW2000 dataset.

**Comment by natanielruiz** [comment]
Good, I'm glad it's resolved. Closing.
