### ISSUE TITLE
Do not understand this predicted angels' calculation, “yaw_predicted = torch.sum(yaw_predicted * idx_tensor, 1).cpu() * 3 - 99”

### ISSUE THREAD

**Issue by AugusTue** [natanielruiz/deep-head-pose#47]
" yaw_predicted = torch.sum(yaw_predicted * idx_tensor, 1).cpu() * 3 - 99
        pitch_predicted = torch.sum(pitch_predicted * idx_tensor, 1).cpu() * 3 - 99
        roll_predicted = torch.sum(roll_predicted * idx_tensor, 1).cpu() * 3 - 99"
Could you please tell me the purpose of this operation and why do this in this way. I cannot understand this. Thanks!

**Comment by AugusTue** [comment]
> ```
>    " yaw_predicted = torch.sum(yaw_predicted * idx_tensor, 1).cpu() * 3 - 99
>     pitch_predicted = torch.sum(pitch_predicted * idx_tensor, 1).cpu() * 3 - 99
>     roll_predicted = torch.sum(roll_predicted * idx_tensor, 1).cpu() * 3 - 99"
> ```
> Could you please tell me the purpose of this operation and why do this in this way. I cannot understand this. Thanks!

**Comment by natanielruiz** [comment]
Please check the paper, the details are explained there.
