### ISSUE TITLE
torch.autograd.backward(loss_seq, grad_seq)      RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]

### ISSUE THREAD

**Issue by gnnbest** [natanielruiz/deep-head-pose#49]
Hi:
    When I run train_hopenet.py, I got this error "RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]", can you tell me how to solve it? thanks very much!!

**Comment by xungeer29** [comment]
Hi, I have the same problem with you and I solve it with @youngliuxx 's answer, but I got another error 'RuntimeError: reduce failed to synchronize: device-side assert triggered', do you know how to solve it?
Error info:
```
Loading data.
/home/anaconda2/lib/python2.7/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Ready to train network.
train_hopenet.py:170: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  yaw_predicted = softmax(yaw)
train_hopenet.py:171: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  pitch_predicted = softmax(pitch)
train_hopenet.py:172: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  roll_predicted = softmax(roll)
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "train_hopenet.py", line 178, in <module>
    loss_reg_yaw = reg_criterion(yaw_predicted, label_yaw_cont)
  File "/home/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/torch/nn/modules/loss.py", line 421, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 1716, in mse_loss
    return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
  File "/home/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 1674, in _pointwise_loss
    return lambd_optimized(input, target, reduction)
RuntimeError: reduce failed to synchronize: device-side assert triggered
```

**Comment by antheazheng** [comment]
Hi @xungeer29,have you solved the problem? 
'RuntimeError: reduce failed to synchronize: device-side assert triggered'

**Comment by natanielruiz** [comment]
@youngliuxx thank you. I believe this is a bug introduced with changes of PyTorch versions, I need to update the code accordingly. Will try to do so when I get some time.

**Comment by CharlesNord** [comment]
> @youngliuxx thank you. I believe this is a bug introduced with changes of PyTorch versions, I need to update the code accordingly. Will try to do so when I get some time.

Why can't we just add the three losses up and do back propagation together? I think it makes no difference with your implementation, since the partial derivative of the total loss to each of the angle's loss is 1.

**Comment by natanielruiz** [comment]
@CharlesNord Yes it should be the same.

**Comment by SnowRipple** [comment]
I'm getting the "RuntimeError: reduce failed to synchronize: device-side assert triggered", how can I fix this? 

@natanielruiz  @CharlesNord  @youngliuxx

**Comment by SnowRipple** [comment]
Anyone?

@natanielruiz @CharlesNord @youngliuxx

**Comment by SnowRipple** [comment]
ok, so it was a problem with the labels going out of range =/- 99 which other people came across too..Using the filtered inputs, solves it :)

**Comment by wangpupanjing** [comment]
@SnowRipple 
which code need to change?

**Comment by SnowRipple** [comment]
@wangpupanjing  you need to use filtered input files (they are provided, it is described in another issue here)

**Comment by flyduck** [comment]
> @wangpupanjing you need to use filtered input files (they are provided, it is described in another issue here)

@SnowRipple  Hi, could you please tell which issue? or tell me how to use filtered input files?thanks
