### ISSUE TITLE
the angle is relative to camera or to people's body?

### ISSUE THREAD

**Issue by MarStarck** [natanielruiz/deep-head-pose#52]
eg, when a people looking upward, but the camera is taking photo from very high position, then the pitch should be negtive. However, if you only consider face, not the whole picture, you may lose this information.

**Comment by marouabenzarti** [comment]
What command did you use to execute the code please ?

**Comment by natanielruiz** [comment]
The angle is relative to the camera coordinates since in the datasets which were used this is the case. Maybe it won't perform well in the case you described since this type of data is not present in the training datasets.

**Comment by DINOUS11** [comment]
> The angle is relative to the camera coordinates since in the datasets which were used this is the case. Maybe it won't perform well in the case you described since this type of data is not present in the training datasets.

@natanielruiz you mean if we put the position of the camera at a suitable height as human eye we can not receive accuracy?
