### ISSUE TITLE
A lite-version hopenet

### ISSUE THREAD

**Issue by OverEuro** [natanielruiz/deep-head-pose#63]
Hi, I have implemented a lite-version hopenet based on **your code**. Specifically speaking, I used ShuffleNet V2 instead of ResNet 50, and this model can run on CPU. Could I release it?

**Comment by natanielruiz** [comment]
This is great, I love it when people expand on this work. Of course you can release it, I'll link to it in the README. Also try to release it with the same open source license as this project for maximum benefit for the community. Cheers!

**Comment by OverEuro** [comment]
Thanks, here is the link:
https://github.com/OverEuro/deep-head-pose-lite

**Comment by natanielruiz** [comment]
Okay. I just linked it. Sorry for the huge delay. I could not do any open source contributions while working at a company (company policy).

Thank you :)
