### ISSUE TITLE
Is anyone getting this kind of error?

### ISSUE THREAD

**Issue by hudingchang** [natanielruiz/deep-head-pose#7]
```
dets = cnn_face_detector(frame, 1)
RuntimeError: Error while calling cudnnSetConvolution2dDescriptor((cudnnConvolutionDescriptor_t)conv_handle, padding_y, padding_x, stride_y, stride_x, 1, 1, CUDNN_CROSS_CORRELATION) in file /tmp/pip-build-BV88Oi/dlib/dlib/dnn/cudnn_dlibapi.cpp:876. code: 3, reason: CUDNN_STATUS_BAD_PARAM
```

**Comment by developer-mayuan** [comment]
@hudingchang I kind had this problem before when running test_on_video_dlib.py, but I can't figure out what's the reason caused this problem.

**Comment by hudingchang** [comment]
@developer-mayuan so, how did you solve it in fact? I don't know why, I can use dlib normally in other condition but not here.

**Comment by natanielruiz** [comment]
Any update on this? @hudingchang @developer-mayuan

**Comment by abhigoku10** [comment]
@developer-mayuan i have faced similar issues , but was able to get the conclusion out of it , when i use dlib in gpu mode i get this error because we need to build dlib from the source for the gpu to access cuda , if your using dlib in cpu mode this error will not be obtained

**Comment by copernicu** [comment]
> ```
> dets = cnn_face_detector(frame, 1)
> RuntimeError: Error while calling cudnnSetConvolution2dDescriptor((cudnnConvolutionDescriptor_t)conv_handle, padding_y, padding_x, stride_y, stride_x, 1, 1, CUDNN_CROSS_CORRELATION) in file /tmp/pip-build-BV88Oi/dlib/dlib/dnn/cudnn_dlibapi.cpp:876. code: 3, reason: CUDNN_STATUS_BAD_PARAM
> ```

did you solve this problem?
