### ISSUE TITLE
Basic running example

### ISSUE THREAD

**Issue by noamzilo** [natanielruiz/deep-head-pose#88]
Hi

I am trying to make this code run, and having some trouble.

`python code/test_on_video_dlib.py --snapshot PATH_OF_SNAPSHOT --face_model PATH_OF_DLIB_MODEL --video PATH_OF_VIDEO --output_string STRING_TO_APPEND_TO_OUTPUT --n_frames N_OF_FRAMES_TO_PROCESS --fps FPS_OF_SOURCE_VIDEO`

What is a snapshot? where do I get one?
What Dlib model do I need? Where do I get the correct one?
Is there a sample video that you tested on?

Just want to make this run, but instructions are not clear to me.

Thanks!

**Comment by natanielruiz** [comment]
Snapshot is the pre-trained model. I have some linked in the README.
Dlib model is the dlib face detections model, google it and try to find it.
Good luck
